import { createElement, useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { HiOutlineArrowRight, HiOutlineBookOpen, HiOutlineCalendar, HiOutlineChartBar, HiOutlineClipboardCheck, HiOutlineFire, HiOutlineStar } from 'react-icons/hi';
import { HiOutlineRocketLaunch } from 'react-icons/hi2';
import { studentAPI } from '../../services/apiService';
import { useAuth } from '../../hooks/useAuth';

const Title=({icon,title,subtitle})=><div className="sd-title"><span>{createElement(icon)}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div>;
const StatCard=({item,navigate})=><button className="sd-stat" onClick={()=>navigate(item.to)}><span className={`sd-stat-icon ${item.tone}`}><item.icon/></span><span><small>{item.title}</small><strong>{item.value}</strong></span></button>;

function Skeleton(){return <div className="student-dashboard sd-skeleton"><i className="sd-sk sd-sk-head"/><div className="sd-stats">{[1,2,3,4].map(i=><i className="sd-sk sd-sk-stat" key={i}/>)}</div><i className="sd-sk sd-sk-course"/><i className="sd-sk sd-sk-upcoming"/></div>}

function ContinueLearning({courses=[]}){return <section className="sd-section"><Title icon={HiOutlineBookOpen} title="Continue Learning" subtitle="Pick up right where you left off"/>{courses.length?<div className="sd-course-list">{courses.map(e=>{const c=e.course||{},p=Math.min(100,Math.max(0,+e.progress||0));return <article className="sd-course" key={e._id}><div className="sd-thumb">{c.thumbnail?<img src={c.thumbnail} alt=""/>:<HiOutlineBookOpen/>}</div><div className="sd-course-body"><div className="sd-course-head"><div><span>{c.category||c.code||'Course'}</span><h3>{c.name||'Course'}</h3>{c.instructor&&<p>with {c.instructor.firstName} {c.instructor.lastName}</p>}</div><strong>{p}% <small>complete</small></strong></div><div className="sd-progress" role="progressbar" aria-valuenow={p}><span style={{width:`${p}%`}}/></div><div className="sd-course-foot"><div><span>Next lesson</span><strong>{e.nextLesson?.title||'Continue where you left off'}</strong></div><Link to={`/student/courses/${c._id}`}>Continue <HiOutlineArrowRight/></Link></div></div></article>})}</div>:<div className="sd-empty-course"><span><HiOutlineRocketLaunch/></span><div><h3>Start your learning journey</h3><p>You haven't enrolled in a course yet. Explore courses and start building your skills.</p></div><Link to="/student/courses" className="sd-primary">Explore Courses <HiOutlineArrowRight/></Link></div>}</section>}

function UpcomingAssessments({items=[]}){
 const dueLabel=value=>{const due=new Date(value),today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((due-today)/86400000);if(days===0)return 'Due today';if(days===1)return 'Due tomorrow';return `Due ${due.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`};
 const typeLabel=type=>type==='topic_test'?'Topic test':type==='final'?'Final assessment':'Practice quiz';
 return <section className="sd-section sd-upcoming"><Title icon={HiOutlineCalendar} title="Upcoming Assessments & Deadlines" subtitle="Stay on top of your upcoming work"/>{items.length?<div className="sd-deadline-list">{items.map(item=><article className="sd-deadline" key={item._id}><span className={`sd-deadline-icon ${item.type}`}><HiOutlineClipboardCheck/></span><div className="sd-deadline-main"><div><span>{typeLabel(item.type)}</span><h3>{item.title}</h3><p>{item.course?.name}{item.topic && <> {'\\u00b7'} {item.topic}</>}</p></div><div className="sd-due"><strong>{dueLabel(item.endDate)}</strong><time dateTime={item.endDate}>{new Date(item.endDate).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</time></div><Link to="/student/assessments" className="sd-deadline-action">{item.type==='practice'?'Attempt quiz':'Start assessment'} <HiOutlineArrowRight/></Link></div></article>)}</div>:<div className="sd-all-caught-up"><span>{String.fromCodePoint(127881)}</span><h3>You're all caught up!</h3><p>No upcoming assessments or deadlines right now.<br/>Keep learning and check back later.</p></div>}</section>
}
export default function StudentDashboard(){
 const {user}=useAuth(),navigate=useNavigate();const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const load=useCallback(async()=>{setError(false);try{const r=await studentAPI.getDashboard();setData(r.data.data)}catch(e){console.error('Dashboard load error:',e);setError(true)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 if(loading)return <Skeleton/>;if(error)return <div className="sd-error"><span>!</span><h2>Couldn't load your learning progress.</h2><p>Your dashboard hit a small snag. Please try again.</p><button onClick={()=>{setLoading(true);load()}}>Try Again</button></div>;
 const s=data?.stats||{};const stats=[['Assessments Taken',s.totalTests||0,HiOutlineClipboardCheck,'indigo','/student/assessments'],['Average Score',`${s.avgScore||0}%`,HiOutlineChartBar,'cyan','/student/performance'],['Learning Streak',`${s.currentStreak||0} Days`,HiOutlineFire,'rose','/student/learning-journey'],['Reward Points',s.totalPoints||0,HiOutlineStar,'amber','/student/rewards']].map(([title,value,icon,tone,to])=>({title,value,icon,tone,to}));
 return <div className="student-dashboard"><i className="sd-glow one"/><i className="sd-glow two"/><header className="sd-header"><div><p>Your learning space</p><h1>Welcome back, {user?.firstName||'Student'}! <span aria-hidden="true">&#128075;</span></h1><span>Here's your learning progress today.</span></div></header><div className="sd-stats">{stats.map(x=><StatCard item={x} navigate={navigate} key={x.title}/>)}</div><ContinueLearning courses={data?.recentCourses}/><UpcomingAssessments items={data?.upcomingAssessments}/></div>;
}
