import VerificationDocumentActions from './VerificationDocumentActions';
import { instructorAPI } from '../../services/apiService';

export default function ReapplicationStatus({ verification: v, eligibility, onEdit, onRefresh }) {
  const locked = eligibility.locked;
  return <section className="mx-auto max-w-3xl rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-6 sm:p-8 text-slate-900 dark:text-slate-100 space-y-5">
    <p className="text-sm font-semibold text-indigo-600 dark:text-indigo-300">Instructor Verification</p>
    <h1 className="text-2xl font-bold">{locked ? 'Reapplication Temporarily Locked' : 'Application Not Approved'}</h1>
    <p>Rejections: <strong>{eligibility.rejectionCount} of 3</strong></p>
    {v.adminMessage && <div className="rounded-xl bg-amber-50 dark:bg-amber-950/40 p-4"><h2 className="font-semibold">Admin Feedback</h2><p className="mt-2 whitespace-pre-wrap break-words">{v.adminMessage}</p></div>}
    {locked ? <><p>You have reached the maximum of 3 rejected verification applications for this period.</p><p>You can apply again after:<br /><strong>{new Date(eligibility.reapplyAvailableAt).toLocaleString()}</strong></p><p className="text-sm text-slate-500 dark:text-slate-400">Your account and documents are retained. Please review your information and supporting documents before applying again.</p><button onClick={onRefresh} className="rounded-xl border px-4 py-2 text-sm">Check eligibility</button></> : <><p>{eligibility.eligibleAgain ? 'You are eligible to reapply for Instructor verification.' : `You may update your application and submit it again. You have ${3 - eligibility.rejectionCount} attempt${3 - eligibility.rejectionCount === 1 ? '' : 's'} remaining during this period.`}</p><button onClick={onEdit} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">{eligibility.eligibleAgain ? 'Review Application' : 'Update Application'}</button></>}
    <details className="rounded-xl border border-slate-200 dark:border-slate-700 p-4"><summary className="cursor-pointer font-semibold">View Application</summary><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[['Organization', v.organization], ['Expertise', v.expertise], ['Qualification', v.qualification], ['Years of Experience', v.experienceYears], ['Professional Profile', v.professionalUrl], ['Professional Bio', v.bio]].map(([label, value]) => <div key={label}><dt className="text-sm text-slate-500 dark:text-slate-400">{label}</dt><dd className="whitespace-pre-wrap break-words">{value ?? 'Not provided'}</dd></div>)}</dl><div className="mt-5 space-y-4">{['resume', 'proof'].map(kind => { const document = v[`${kind}Document`]; return document?.storageId ? <div key={kind}><p className="mb-2 break-all text-sm">{document.originalName}</p><VerificationDocumentActions document={document} label={kind === 'resume' ? 'Resume' : 'Proof'} loadDocument={() => instructorAPI.getDocument(kind)} /></div> : null; })}</div></details>
  </section>;
}
